### ISSUE TITLE
Not generating a list of stocks 

### ISSUE THREAD

**Issue by itwasallme** [steveman1123/stonkBot#4] opened 2020-09-11 14:23 UTC
When I run the main file. There is a constant loop, looks like it can't build a list of stocks. 
![Capture](https://user-images.githubusercontent.com/47570208/92937072-dfd6a500-f418-11ea-8247-aa8f6810eebe.PNG)

**Comment by steveman1123** [comment] 2020-09-11 14:34
It should start looking to buimd the list 20 minutes before close. You can
set that time to be earlier by changing the updateListTime to a larger
value (e.g. to update at noon EST, it'd be 180). I haven't confirmed if it
works or not since I've changed it, so if the issue persists after that,
feel free to respond

itwasallme <notifications@github.com> schrieb am Fr., 11. Sep. 2020, 09:24:

**Comment by itwasallme** [comment] 2020-09-11 16:06
I increased the window but still no luck

**Comment by steveman1123** [comment] 2020-09-11 16:23
You may have a permission issue? I usually run mine as sudo because I haven't set the permissions of the stock data folder properly

**Comment by itwasallme** [comment] 2020-09-11 19:51
@steveman1123  what Nasdaq api product are you using have a hard time finding the documentation

**Comment by steveman1123** [comment] 2020-09-11 19:54
See the links in the README. I also could not find any documentation. If you do find something, please send me a link!

**Comment by GitHubEmploy** [comment] 2020-09-14 20:57
This also happened to me, you need to first access the website and see if you can access the stocks, and if you can't, that means that your wifi cache if full and you need to restart your router. If you can, that means that it encountered a fatal error in one of the loops, and the code found a loophole and exited into no connection. Then you would need to refer to the docs. This is just a small comment to keep in mind. 😁

**Comment by GitHubEmploy** [comment] 2020-09-15 16:36
I had this same problem just restart the code and it should work.

**Comment by steveman1123** [comment] 2020-09-17 01:49
Okay, so I added some timeouts to all the requests, so if you pull the latest version, it _should_ fix that, as far as I know

**Comment by GitHubEmploy** [comment] 2020-09-17 01:57
The new version works perfectly, so I will close this now

**Closed** 2020-09-17 02:02 UTC
